config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "groups#index"

  resources :groups,except: [:show,:destroy] do
    resources :messages,only: [:index,:create]
  end
  resources :users do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true

  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :message_or_image, presence: true

  belongs_to :user
  belongs_to :group

  private
    def message_or_image
      message.present? || image.present?
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, :email, presence: true
  # validates :encrypted_password, presence: true, length: { minimum: 8 }

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages

  scope :search_by_name, ->(keyword, current_user){ where('name LIKE(?)', "%#{keyword}%").where.not(id: current_user.id) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
    @groups = current_user.groups.order('created_at DESC')
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.users << current_user
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました。'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path, notice: 'チャットグループが更新されました'
    else
      render :edit
    end
  end

  private

  def group_params
     params.require(:group).permit(:name, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :set_group, only: [:index, :create]

  def index
    @message = Message.new
    @messages = @group.messages.order(created_at: :ASC).includes(:user)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @message = @group.messages.new(create_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path }
        format.json
      end
    else
      flash.now[:alert] = "メッセージを入力してください"
      render :index
    end
  end

  private

  def create_params
    params.require(:message).permit(:message,:image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.search_by_name(params[:keyword], current_user)

    render json: @users
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if current_user.update(user_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:users).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  .chat-group-form__errors
    - if @group.errors.any?
      %ul
        -@group.errors.full_messages.each do |message|
          %li
            =message
  = render "layouts/group-edit"

app/views/groups/index.html.haml
.chat-side
  = render "layouts/user"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  .chat-group-form__errors
    - if @group.errors.present?
      %h2 #{@group.errors.full_messages.count}件のエラーが発生しました。
      %ul
        -@group.errors.full_messages.each do |message|
          %li
            =message
  = render "layouts/group-new"

app/views/layouts/_chat-side__groups-list.html.haml
.chat-side__groups-list
  %li.chat-side__groupe
    テンプレート
    %p.chat-side__groupe-name
      テンプレート

app/views/layouts/_flash.html.haml
.notification-alert
  - flash.each do |key, value|
    = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/_group-edit.html.haml
= form_for @group do |f|
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, "グループ名", class: "chat-group-form__label"
    .chat-group-form__field--right
      = f.text_field :name, placeholder: "グループ名を入力してくだい", class: "chat-group-form__input"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", type: "text"}/
        %p.chat-group-user__name
          %ul#result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, "チャットメンバー", class: "chat-group-form__label"
    .chat-group-form__field--right
      #chat-group-users
      = current_user.name
      %ul.result-list
  #chat-group-user-22.chat-group-user.clearfix
    %input{name: "chat_group[user_ids][]", type: "hidden", value: "22"}/


  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit "Save", class: "chat-group-form__action-btn", url: "/groups/new"

app/views/layouts/_group-new.html.haml
= form_for @group do |f|
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, "グループ名", class: "chat-group-form__label"
    .chat-group-form__field--right
      = f.text_field :name, placeholder: "グループ名を入力してください", class: "chat-group-form__input"
  .chat-group-form__field.clearfix

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, "チャットメンバー", class: "chat-group-form__label"
    .chat-group-form__field--right
      = f.collection_check_boxes :user_ids, User.all, :id, :name do |t|
        = t.label{ t.check_box + t.text }

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit "Save", class: "chat-group-form__action-btn"

app/views/layouts/_groups-list.html.haml
%ul.chat-side__groups
  .chat-side__groups-list
    - current_user.groups.each do |group|
      %li.chat-side__group
        = link_to group_messages_path(group) do
          %p.chat-side__group-name
            = group.name
          %p.chat-side__group-message
            ooooo

app/views/layouts/_user.html.haml
.chat-side__user
  .chat-side__user-content
    .chat-side__user-name
      - if user_signed_in?
        = current_user.name
    .chat-side__user-btn
      %a.chat-side__group-create
        = link_to new_group_path do
          %i.fa.fa-pencil-square-o
      %a.chat-side__user-config
        = link_to edit_user_registration_path do
          %i.fa.fa-cog
.chat-side--groups
  = render "layouts/groups-list"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content:  "text/html; charset=UTF-8", "http-equiv":"Content-Type"}/
    %title ChatSpace
    %script{:src => "http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js", :type => "text/javascript"}
    %script{:src => "/flashs.json"}
    %script{:src => "/messages.json"}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .wrapper
      .notification
        = render "layouts/flash"
      = yield

app/views/messages/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/messages/index.html.haml
.wrapper
  .chat-side
    = render "layouts/user"
  .chat-main
    .chat-main__header
      .chat-main__header--group
        .chat-main__header--group-name
          = @group.name
        %a.chat-main__header--group-edit-btn{href:"/groups/#{@group.id}/edit"}
          %input{type: "submit",value: "Edit"}
      .chat-main__header-members
        MEMBER:
        %i
          = @group.users.name
    .chat-main__body
      .chat-main__body--messages-list
        %ul.chat-main__message-ul
          - @group.messages.each do |message|
            %li.chat-main__message
              %p.chat-main__message-name
                = message.user.name
              %p.chat-main__message-time
                = message.created_at
              %p.chat-main__message-body
                = message.message
                = image_tag message.image.thumb
    .chat-main__footer
      =form_for [@group,@message] do |f|
        .chat-main__footer-body
          = f.text_field :message, placeholder: "  type a message", class: "chat-main__message-send"
          .chat-main__footer-body-sentbtn
            = f.submit "send", data: { disable_with: '更新中...' }
        .chat-main__footer-image
          = f.label :image do
            %i.fa.fa-picture-o
          = f.file_field :image